[2023-09-06T12:55:20.258+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_operator_dag.create_pet_table scheduled__2020-02-02T00:00:00+00:00 [queued]>
[2023-09-06T12:55:20.262+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_operator_dag.create_pet_table scheduled__2020-02-02T00:00:00+00:00 [queued]>
[2023-09-06T12:55:20.263+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-09-06T12:55:20.273+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_pet_table> on 2020-02-02 00:00:00+00:00
[2023-09-06T12:55:20.277+0000] {standard_task_runner.py:57} INFO - Started process 337 to run task
[2023-09-06T12:55:20.281+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_operator_dag', 'create_pet_table', 'scheduled__2020-02-02T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/postgres_operator.py', '--cfg-path', '/tmp/tmpphspswbq']
[2023-09-06T12:55:20.282+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask create_pet_table
[2023-09-06T12:55:20.315+0000] {task_command.py:415} INFO - Running <TaskInstance: postgres_operator_dag.create_pet_table scheduled__2020-02-02T00:00:00+00:00 [running]> on host 80a7ead3f1b6
[2023-09-06T12:55:20.364+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_operator_dag' AIRFLOW_CTX_TASK_ID='create_pet_table' AIRFLOW_CTX_EXECUTION_DATE='2020-02-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2020-02-02T00:00:00+00:00'
[2023-09-06T12:55:20.365+0000] {sql.py:274} INFO - Executing: 
            SELECT * FROM "Album";
          
[2023-09-06T12:55:20.370+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-09-06T12:55:20.378+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-09-06T12:55:20.380+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 154, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "postgres" (172.23.0.3), port 5432 failed: FATAL:  database "public" does not exist

[2023-09-06T12:55:20.384+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=postgres_operator_dag, task_id=create_pet_table, execution_date=20200202T000000, start_date=20230906T125520, end_date=20230906T125520
[2023-09-06T12:55:20.464+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 9 for task create_pet_table (connection to server at "postgres" (172.23.0.3), port 5432 failed: FATAL:  database "public" does not exist
; 337)
[2023-09-06T12:55:20.492+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-06T12:55:20.505+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
