[2023-09-06T12:55:23.504+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_operator_dag.create_pet_table manual__2023-09-06T12:55:22.365315+00:00 [queued]>
[2023-09-06T12:55:23.511+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_operator_dag.create_pet_table manual__2023-09-06T12:55:22.365315+00:00 [queued]>
[2023-09-06T12:55:23.511+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-09-06T12:55:23.523+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_pet_table> on 2023-09-06 12:55:22.365315+00:00
[2023-09-06T12:55:23.529+0000] {standard_task_runner.py:57} INFO - Started process 340 to run task
[2023-09-06T12:55:23.531+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_operator_dag', 'create_pet_table', 'manual__2023-09-06T12:55:22.365315+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/postgres_operator.py', '--cfg-path', '/tmp/tmpex81ggp3']
[2023-09-06T12:55:23.533+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask create_pet_table
[2023-09-06T12:55:23.576+0000] {task_command.py:415} INFO - Running <TaskInstance: postgres_operator_dag.create_pet_table manual__2023-09-06T12:55:22.365315+00:00 [running]> on host 80a7ead3f1b6
[2023-09-06T12:55:23.630+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_operator_dag' AIRFLOW_CTX_TASK_ID='create_pet_table' AIRFLOW_CTX_EXECUTION_DATE='2023-09-06T12:55:22.365315+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-06T12:55:22.365315+00:00'
[2023-09-06T12:55:23.632+0000] {sql.py:274} INFO - Executing: 
            SELECT * FROM "Album";
          
[2023-09-06T12:55:23.637+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-09-06T12:55:23.643+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-09-06T12:55:23.645+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 154, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "postgres" (172.23.0.3), port 5432 failed: FATAL:  database "public" does not exist

[2023-09-06T12:55:23.651+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=postgres_operator_dag, task_id=create_pet_table, execution_date=20230906T125522, start_date=20230906T125523, end_date=20230906T125523
[2023-09-06T12:55:23.661+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 10 for task create_pet_table (connection to server at "postgres" (172.23.0.3), port 5432 failed: FATAL:  database "public" does not exist
; 340)
[2023-09-06T12:55:23.703+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-06T12:55:23.715+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
