[2023-09-13T13:19:16.226+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: artis_revenue.insert_into_artist_revenue manual__2023-09-13T13:19:14.655835+00:00 [queued]>
[2023-09-13T13:19:16.232+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: artis_revenue.insert_into_artist_revenue manual__2023-09-13T13:19:14.655835+00:00 [queued]>
[2023-09-13T13:19:16.232+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-09-13T13:19:16.242+0000] {taskinstance.py:1382} INFO - Executing <Task(GenericTransfer): insert_into_artist_revenue> on 2023-09-13 13:19:14.655835+00:00
[2023-09-13T13:19:16.247+0000] {standard_task_runner.py:57} INFO - Started process 1079 to run task
[2023-09-13T13:19:16.249+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'artis_revenue', 'insert_into_artist_revenue', 'manual__2023-09-13T13:19:14.655835+00:00', '--job-id', '159', '--raw', '--subdir', 'DAGS_FOLDER/artist_revenue.py', '--cfg-path', '/tmp/tmpwcpy34ph']
[2023-09-13T13:19:16.250+0000] {standard_task_runner.py:85} INFO - Job 159: Subtask insert_into_artist_revenue
[2023-09-13T13:19:16.280+0000] {task_command.py:415} INFO - Running <TaskInstance: artis_revenue.insert_into_artist_revenue manual__2023-09-13T13:19:14.655835+00:00 [running]> on host bdff3168b881
[2023-09-13T13:19:16.338+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Aditiya Rahman' AIRFLOW_CTX_DAG_ID='artis_revenue' AIRFLOW_CTX_TASK_ID='insert_into_artist_revenue' AIRFLOW_CTX_EXECUTION_DATE='2023-09-13T13:19:14.655835+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-13T13:19:14.655835+00:00'
[2023-09-13T13:19:16.344+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-09-13T13:19:16.359+0000] {base.py:73} INFO - Using connection ID 'datawarehouse' for task execution.
[2023-09-13T13:19:16.359+0000] {generic_transfer.py:77} INFO - Extracting data from postgres
[2023-09-13T13:19:16.360+0000] {generic_transfer.py:78} INFO - Executing: 
 
SELECT a."ArtistId", 
       a."Name", 
       b."Title", 
       c."Name", 
       (d."Quantity" * d."UnitPrice"),
       d."InvoiceLineId",
       e."InvoiceId",
       e."InvoiceDate"
FROM "Artist" a
JOIN "Album" b
ON a."ArtistId" = b."ArtistId"
JOIN "Track" c
ON b."AlbumId" = c."AlbumId"
JOIN "InvoiceLine" d
ON c."TrackId" = d."TrackId"
JOIN "Invoice" e
ON d."InvoiceId" = e."InvoiceId"
[2023-09-13T13:19:16.363+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-09-13T13:19:16.366+0000] {sql.py:418} INFO - Running statement: 
SELECT a."ArtistId", 
       a."Name", 
       b."Title", 
       c."Name", 
       (d."Quantity" * d."UnitPrice"),
       d."InvoiceLineId",
       e."InvoiceId",
       e."InvoiceDate"
FROM "Artist" a
JOIN "Album" b
ON a."ArtistId" = b."ArtistId"
JOIN "Track" c
ON b."AlbumId" = c."AlbumId"
JOIN "InvoiceLine" d
ON c."TrackId" = d."TrackId"
JOIN "Invoice" e
ON d."InvoiceId" = e."InvoiceId", parameters: None
[2023-09-13T13:19:16.377+0000] {sql.py:427} INFO - Rows affected: 2240
[2023-09-13T13:19:16.381+0000] {generic_transfer.py:95} INFO - Running preoperator
[2023-09-13T13:19:16.381+0000] {generic_transfer.py:96} INFO - ['DROP TABLE IF EXISTS artist_revenue']
[2023-09-13T13:19:16.386+0000] {base.py:73} INFO - Using connection ID 'datawarehouse' for task execution.
[2023-09-13T13:19:16.388+0000] {sql.py:418} INFO - Running statement: DROP TABLE IF EXISTS artist_revenue, parameters: None
[2023-09-13T13:19:16.396+0000] {generic_transfer.py:105} INFO - Inserting rows into datawarehouse
[2023-09-13T13:19:16.402+0000] {base.py:73} INFO - Using connection ID 'datawarehouse' for task execution.
[2023-09-13T13:19:16.405+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/generic_transfer.py", line 106, in execute
    insert_rows(table=self.destination_table, rows=results, **self.insert_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 509, in insert_rows
    cur.execute(sql, values)
psycopg2.errors.UndefinedTable: relation "artist_revenue" does not exist
LINE 1: INSERT INTO artist_revenue  VALUES (2,'Accept','Balls to the...
                    ^

[2023-09-13T13:19:16.413+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=artis_revenue, task_id=insert_into_artist_revenue, execution_date=20230913T131914, start_date=20230913T131916, end_date=20230913T131916
[2023-09-13T13:19:16.426+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 159 for task insert_into_artist_revenue (relation "artist_revenue" does not exist
LINE 1: INSERT INTO artist_revenue  VALUES (2,'Accept','Balls to the...
                    ^
; 1079)
[2023-09-13T13:19:16.461+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-13T13:19:16.506+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
