[2023-09-13T14:46:04.518+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: business_question.insert_into_artist_earnings manual__2023-09-13T14:46:00.129015+00:00 [queued]>
[2023-09-13T14:46:04.523+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: business_question.insert_into_artist_earnings manual__2023-09-13T14:46:00.129015+00:00 [queued]>
[2023-09-13T14:46:04.524+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-09-13T14:46:04.535+0000] {taskinstance.py:1382} INFO - Executing <Task(GenericTransfer): insert_into_artist_earnings> on 2023-09-13 14:46:00.129015+00:00
[2023-09-13T14:46:04.540+0000] {standard_task_runner.py:57} INFO - Started process 2433 to run task
[2023-09-13T14:46:04.542+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'business_question', 'insert_into_artist_earnings', 'manual__2023-09-13T14:46:00.129015+00:00', '--job-id', '167', '--raw', '--subdir', 'DAGS_FOLDER/business_question.py', '--cfg-path', '/tmp/tmp7kpwj7es']
[2023-09-13T14:46:04.544+0000] {standard_task_runner.py:85} INFO - Job 167: Subtask insert_into_artist_earnings
[2023-09-13T14:46:04.577+0000] {task_command.py:415} INFO - Running <TaskInstance: business_question.insert_into_artist_earnings manual__2023-09-13T14:46:00.129015+00:00 [running]> on host bdff3168b881
[2023-09-13T14:46:04.633+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Aditiya Rahman' AIRFLOW_CTX_DAG_ID='business_question' AIRFLOW_CTX_TASK_ID='insert_into_artist_earnings' AIRFLOW_CTX_EXECUTION_DATE='2023-09-13T14:46:00.129015+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-13T14:46:00.129015+00:00'
[2023-09-13T14:46:04.638+0000] {base.py:73} INFO - Using connection ID 'datawarehouse' for task execution.
[2023-09-13T14:46:04.649+0000] {base.py:73} INFO - Using connection ID 'datamart' for task execution.
[2023-09-13T14:46:04.649+0000] {generic_transfer.py:77} INFO - Extracting data from datawarehouse
[2023-09-13T14:46:04.650+0000] {generic_transfer.py:78} INFO - Executing: 
 
SELECT "ArtistId", "ArtistName", SUM("TotalPrice") AS "Earnings"
FROM "artist_revenue"
GROUP BY "ArtistId", "ArtistName"
ORDER BY "Earnings" DESC
[2023-09-13T14:46:04.653+0000] {base.py:73} INFO - Using connection ID 'datawarehouse' for task execution.
[2023-09-13T14:46:04.655+0000] {sql.py:418} INFO - Running statement: 
SELECT "ArtistId", "ArtistName", SUM("TotalPrice") AS "Earnings"
FROM "artist_revenue"
GROUP BY "ArtistId", "ArtistName"
ORDER BY "Earnings" DESC, parameters: None
[2023-09-13T14:46:04.657+0000] {sql.py:427} INFO - Rows affected: 165
[2023-09-13T14:46:04.658+0000] {generic_transfer.py:95} INFO - Running preoperator
[2023-09-13T14:46:04.658+0000] {generic_transfer.py:96} INFO - ['DROP TABLE IF EXISTS artist_earnings', '\n        CREATE TABLE artist_earnings (\n        "ArtistId" INT NOT NULL,\n        "ArtistName" VARCHAR(120),\n        "Earnings" NUMBERIC(10,2) NOT NULL\n        )\n        ']
[2023-09-13T14:46:04.662+0000] {base.py:73} INFO - Using connection ID 'datamart' for task execution.
[2023-09-13T14:46:04.664+0000] {sql.py:418} INFO - Running statement: DROP TABLE IF EXISTS artist_earnings, parameters: None
[2023-09-13T14:46:04.664+0000] {sql.py:418} INFO - Running statement: 
        CREATE TABLE artist_earnings (
        "ArtistId" INT NOT NULL,
        "ArtistName" VARCHAR(120),
        "Earnings" NUMBERIC(10,2) NOT NULL
        )
        , parameters: None
[2023-09-13T14:46:04.665+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/generic_transfer.py", line 97, in execute
    run(self.preoperator)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedObject: type "numberic" does not exist
LINE 5:         "Earnings" NUMBERIC(10,2) NOT NULL
                           ^

[2023-09-13T14:46:04.670+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=business_question, task_id=insert_into_artist_earnings, execution_date=20230913T144600, start_date=20230913T144604, end_date=20230913T144604
[2023-09-13T14:46:04.680+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 167 for task insert_into_artist_earnings (type "numberic" does not exist
LINE 5:         "Earnings" NUMBERIC(10,2) NOT NULL
                           ^
; 2433)
[2023-09-13T14:46:04.714+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-13T14:46:04.732+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
