[2023-09-09T14:15:18.085+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: artis_revenue.create_table manual__2023-09-09T14:10:41.972157+00:00 [queued]>
[2023-09-09T14:15:18.090+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: artis_revenue.create_table manual__2023-09-09T14:10:41.972157+00:00 [queued]>
[2023-09-09T14:15:18.090+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-09-09T14:15:18.098+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_table> on 2023-09-09 14:10:41.972157+00:00
[2023-09-09T14:15:18.102+0000] {standard_task_runner.py:57} INFO - Started process 398 to run task
[2023-09-09T14:15:18.104+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'artis_revenue', 'create_table', 'manual__2023-09-09T14:10:41.972157+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/artist_revenue.py', '--cfg-path', '/tmp/tmpno9t8d2l']
[2023-09-09T14:15:18.106+0000] {standard_task_runner.py:85} INFO - Job 77: Subtask create_table
[2023-09-09T14:15:18.133+0000] {task_command.py:415} INFO - Running <TaskInstance: artis_revenue.create_table manual__2023-09-09T14:10:41.972157+00:00 [running]> on host 80a7ead3f1b6
[2023-09-09T14:15:18.178+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Aditiya Rahman' AIRFLOW_CTX_DAG_ID='artis_revenue' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2023-09-09T14:10:41.972157+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-09T14:10:41.972157+00:00'
[2023-09-09T14:15:18.179+0000] {sql.py:274} INFO - Executing: 
CREATE TABLE "artist_revenue" (
    "ArtistId" INT NOT NULL,
    "ArtistName" VARCHAR(120),
    "AlbumTitle" VARCHAR(160) NOT NULL,
    "TrackName" VARCHAR(200) NOT NULL,
    "TotalPrice" NUMERIC(10,2) NOT NULL,
    "InvoiceLineId" INT NOT NULL,
    "InvoiceId" INT NOT NULL,
    "InvoiceDate" TIMESTAMP NOT NULL
);
[2023-09-09T14:15:18.184+0000] {base.py:73} INFO - Using connection ID 'datawarehouse' for task execution.
[2023-09-09T14:15:18.188+0000] {base.py:73} INFO - Using connection ID 'datawarehouse' for task execution.
[2023-09-09T14:15:18.190+0000] {sql.py:418} INFO - Running statement: 
CREATE TABLE "artist_revenue" (
    "ArtistId" INT NOT NULL,
    "ArtistName" VARCHAR(120),
    "AlbumTitle" VARCHAR(160) NOT NULL,
    "TrackName" VARCHAR(200) NOT NULL,
    "TotalPrice" NUMERIC(10,2) NOT NULL,
    "InvoiceLineId" INT NOT NULL,
    "InvoiceId" INT NOT NULL,
    "InvoiceDate" TIMESTAMP NOT NULL
);, parameters: None
[2023-09-09T14:15:18.191+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.DuplicateTable: relation "artist_revenue" already exists

[2023-09-09T14:15:18.196+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=artis_revenue, task_id=create_table, execution_date=20230909T141041, start_date=20230909T141518, end_date=20230909T141518
[2023-09-09T14:15:18.203+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 77 for task create_table (relation "artist_revenue" already exists
; 398)
[2023-09-09T14:15:18.236+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-09T14:15:18.250+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
